// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rawsfepukwpfwhmonlvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhd3NmZXB1a3dwZndobW9ubHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDQ4MjUsImV4cCI6MjA2NTIyMDgyNX0.0zZioxzz7AOiL5tR8JkizT_oPziNq4gGHf-EIlSsQWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);